-- Migration 010: Student Enrollment Schema
-- Adds comprehensive columns to students table for a full rebuild

ALTER TABLE students
ADD COLUMN sr_no VARCHAR(100) NULL,
ADD COLUMN first_name VARCHAR(100) NULL,
ADD COLUMN middle_name VARCHAR(100) NULL,
ADD COLUMN last_name VARCHAR(100) NULL,
ADD COLUMN gender VARCHAR(20) NULL,
ADD COLUMN blood_group VARCHAR(10) NULL,
ADD COLUMN category VARCHAR(50) NULL,
ADD COLUMN religion VARCHAR(50) NULL,
ADD COLUMN aadhaar_no VARCHAR(50) NULL,
ADD COLUMN student_mobile VARCHAR(30) NULL,
ADD COLUMN student_email VARCHAR(200) NULL,
ADD COLUMN academic_year_id INT NULL,
ADD COLUMN admission_date DATE NULL,
ADD COLUMN roll_no VARCHAR(50) NULL,
ADD COLUMN house VARCHAR(50) NULL,
ADD COLUMN father_name VARCHAR(200) NULL,
ADD COLUMN father_phone VARCHAR(30) NULL,
ADD COLUMN father_email VARCHAR(200) NULL,
ADD COLUMN father_occupation VARCHAR(100) NULL,
ADD COLUMN mother_name VARCHAR(200) NULL,
ADD COLUMN mother_phone VARCHAR(30) NULL,
ADD COLUMN mother_email VARCHAR(200) NULL,
ADD COLUMN mother_occupation VARCHAR(100) NULL,
ADD COLUMN guardian_name VARCHAR(200) NULL,
ADD COLUMN guardian_relation VARCHAR(100) NULL,
ADD COLUMN guardian_phone VARCHAR(30) NULL,
ADD COLUMN current_address_line TEXT NULL,
ADD COLUMN current_city VARCHAR(100) NULL,
ADD COLUMN current_state VARCHAR(100) NULL,
ADD COLUMN current_country VARCHAR(100) NULL,
ADD COLUMN current_pin_code VARCHAR(20) NULL,
ADD COLUMN permanent_address_line TEXT NULL,
ADD COLUMN permanent_city VARCHAR(100) NULL,
ADD COLUMN permanent_state VARCHAR(100) NULL,
ADD COLUMN permanent_country VARCHAR(100) NULL,
ADD COLUMN permanent_pin_code VARCHAR(20) NULL,
ADD COLUMN same_as_current TINYINT(1) DEFAULT 0,
ADD COLUMN allergies TEXT NULL,
ADD COLUMN medical_conditions TEXT NULL,
ADD COLUMN emergency_contact VARCHAR(100) NULL,
ADD COLUMN doctor_name VARCHAR(200) NULL,
ADD COLUMN transport_required TINYINT(1) DEFAULT 0,
ADD COLUMN transport_route VARCHAR(200) NULL,
ADD COLUMN transport_pickup_point VARCHAR(200) NULL,
ADD COLUMN hostel_required TINYINT(1) DEFAULT 0,
ADD COLUMN hostel_name VARCHAR(200) NULL,
ADD COLUMN hostel_room_number VARCHAR(50) NULL,
ADD COLUMN photo_path VARCHAR(255) NULL,
ADD COLUMN birth_cert_path VARCHAR(255) NULL,
ADD COLUMN aadhaar_path VARCHAR(255) NULL,
ADD COLUMN transfer_cert_path VARCHAR(255) NULL,
ADD COLUMN report_card_path VARCHAR(255) NULL,
ADD COLUMN additional_docs_path VARCHAR(255) NULL,
ADD CONSTRAINT fk_student_academic_year FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE SET NULL;
