CREATE TABLE IF NOT EXISTS academic_achievement_snapshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    school_id INT NOT NULL,
    academic_year_id INT NOT NULL,
    feature_type VARCHAR(50) NOT NULL,
    class_id INT NULL,
    student_id INT NOT NULL,
    student_name VARCHAR(255) NOT NULL,
    student_photo TEXT NULL,
    class_name VARCHAR(100) NOT NULL,
    roll_number VARCHAR(50) NULL,
    achievement_score DECIMAL(5,2) NOT NULL,
    `rank` INT NOT NULL,
    metadata JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
    FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE CASCADE,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
    INDEX idx_achievement_lookup (school_id, academic_year_id, feature_type, class_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
